services:

  jenkins:
    container_name: jenkins
    networks:
      - jenkins   
    image: jenkins/jenkins:2.504.1-lts-jdk21
    ports:
      - 8080:8080
      - 50000:50000
    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: 1
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-cert:/certs/client:ro

  jenkins-agent:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: jenkins-agent
    depends_on:
      - jenkins
    environment:
      JENKINS_URL: "$jenkins_url"
      JENKINS_AGENT_NAME: "$jenkins_name"
      JENKINS_SECRET: "$jenkins_secret"
      WEBSOCKET: true
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins
      
volumes: 
  jenkins-data:
  jenkins-cert:

networks:
  jenkins:
    driver: bridge
