# Use official Jenkins agent base image
FROM jenkins/inbound-agent:jdk21

USER root

# Install Go
ENV GO_VERSION=1.24.0

RUN curl -OL https://golang.org/dl/go${GO_VERSION}.linux-amd64.tar.gz \
    && tar -C /usr/local -xzf go${GO_VERSION}.linux-amd64.tar.gz \
    && rm go${GO_VERSION}.linux-amd64.tar.gz

ENV PATH="/usr/local/go/bin:$PATH"

# Verify installation
RUN go version

USER jenkins